RESET MASTER;
CHANGE MASTER TO MASTER_HOST='node_000', MASTER_PORT=3306, MASTER_USER='skysql', MASTER_PASSWORD='skysql', MASTER_USE_GTID=slave_pos, MASTER_CONNECT_RETRY=1;
START SLAVE;
SET GLOBAL max_connections=10000;
-- SET GLOBAL gtid_strict_mode=ON;
